### ISSUE TITLE
Redundant & inconsistent function names

### ISSUE THREAD

**Issue by PatrickGTR** [emmett-white/SA-MP#1]
``Rent_CreateRent`` ->``Rent_Create``
``Rent_GoToRent`` -> ``Rent_Goto``
``Rent_DeleteRent`` -> ``Rent_Delete``
``LoadRents`` -> ``Rent_Load``
 

``const i`` -> ``const id`` 
i should only be used in loops, what if you have to create a loop inside that function?

**Comment by emmett-white** [comment]
> `Rent_CreateRent` ->`Rent_Create`
> `Rent_GoToRent` -> `Rent_Goto`
> `Rent_DeleteRent` -> `Rent_Delete`
> `LoadRents` -> `Rent_Load`
> 
> `const i` -> `const id`
> i should only be used in loops, what if you have to create a loop inside that function?

Now that I look, I'm really an idiot sometimes..

**Comment by PatrickGTR** [comment]
seems to be fixed, closing this.
